services:
  dennis-cv:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dennis-cv
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
